// generated by stringer -type=blockType; DO NOT EDIT

package mdfmt

import "fmt"

const _blockType_name = "BT_ERRORBT_BLOCK_QUOTEBT_LIST_ITEMBT_LISTBT_ATX_HEADERBT_SETEXT_HEADERBT_CODE_BLOCKBT_PARAGRAPH"

var _blockType_index = [...]uint8{0, 8, 22, 34, 41, 54, 70, 83, 95}

func (i blockType) String() string {
	if i < 0 || i+1 >= blockType(len(_blockType_index)) {
		return fmt.Sprintf("blockType(%d)", i)
	}
	return _blockType_name[_blockType_index[i]:_blockType_index[i+1]]
}
